### PR TITLE
Add testing script for interim site as an on demand workflow

### PR DESCRIPTION
**Pull request by peterdavidhamilton**
Successful run:
https://github.com/DFE-Digital/ey-recovery-prototype/runs/6423425997?check_suite_focus=true

### CODE REVIEW

**Comment by agoldstone93** [comment]
I dont know if this is appropriate because:
1. I dont think we're going to be making any changes to this interim site after today
2. It's currently making the checks against a deployed site so if you introduce / fix issues in a PR, they wouldn't be picked up in this github action

What do you think @peterdavidhamilton?

**Comment by peterdavidhamilton** [comment]
> I dont know if this is appropriate because:
> 
> 1. I dont think we're going to be making any changes to this interim site after today
> 2. It's currently making the checks against a deployed site so if you introduce / fix issues in a PR, they wouldn't be picked up in this github action
> 
> What do you think @peterdavidhamilton?

Valid points @agoldstone93. I know @timallen-and is still working on scripting pa11y I thought we should get it this committed at least. The workflow needs to be run manually so the intention was just to make it available to content designers;  I thought they were also applying fixes.

**Comment by agoldstone93** [comment]
> > I dont know if this is appropriate because:
> > 
> > 1. I dont think we're going to be making any changes to this interim site after today
> > 2. It's currently making the checks against a deployed site so if you introduce / fix issues in a PR, they wouldn't be picked up in this github action
> > 
> > What do you think @peterdavidhamilton?
> 
> Valid points @agoldstone93. I know @timallen-and is still working on scripting pa11y I thought we should get it this committed at least. The workflow needs to be run manually so the intention was just to make it available to content designers; I thought they were also applying fixes.

Fair enough. In which case, can you make the changes i've suggested above as Tim's list of pages are outdated

**Comment by peterdavidhamilton** [comment]
Cheers for the changes @agoldstone93

**Review by agoldstone93 — APPROVED** [review]

**Review by agoldstone93 — APPROVED** [review]

**Pull request merged**
